<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0lwp2ve\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0lwp2ve/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0lwp2ve.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0lwp2ve\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0lwp2ve\appProdProjectContainer([
    'container.build_hash' => '0lwp2ve',
    'container.build_id' => '5474117b',
    'container.build_time' => 1595181648,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0lwp2ve');
